//====================================================================================================
// Base code generated with LeatherGoods - ASF.Services.Contracts
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using ASF.Entities;
using ASF.Data.DbContext;



namespace ASF.Services.Contracts
{

    [DataContract]
    public class AllResponse
    {
        [DataMember]
        public List<Entities.Category> Result { get; set; }

        [DataMember]
        public List<Entities.Country> ResultCountry { get; set; }

        [DataMember]
        public List<Data.DbContext.Client> ResultClient{ get; set; }

        [DataMember]
        public List<Entities.Dealer> ResultDealer { get; set; }

        [DataMember]
        public List<Entities.Product> ResultProduct { get; set; }
    }
}

